### ISSUE TITLE
Support GNOME 44

### ISSUE THREAD

**Issue by sfllaw** [daitj/gnome-display-brightness-ddcutil#103]
It looks like bumping the version in metadata.json is sufficient.

**Comment by pktpls** [comment]
:+1: 

It even integrates into menu nicer than it did in 43.

![image](https://user-images.githubusercontent.com/59322297/234925695-7e41db49-27d1-4982-950d-282f9c687a88.png)

**Comment by jixbo** [comment]
Are you sure that is the external screen brightness?
It works as it used to work for me, which is fine. Tested with version 44 bump and no issues, so opened a MR:

https://github.com/daitj/gnome-display-brightness-ddcutil/pull/104

**Comment by pktpls** [comment]
> Are you sure that is the external screen brightness?

Yes, I only have that one external screen, and it correctly changes brightness :-)

**Comment by daitj** [comment]
@pktpls
I rewrote the code of sliders to have better support for new gnome settings and also fixed the position the sliders in system menu in March (extension version: 37). It should have been better looking after that.

I will update the extension's metadata and upload it to gnome.

**Comment by pktpls** [comment]
Thanks friend :-)
