### ISSUE TITLE
Not detecting primary display

### ISSUE THREAD

**Issue by juladuni** [daitj/gnome-display-brightness-ddcutil#105]
Hi,

'ddcutil detect' gets both of my displays and i can control the brightness of both of them via command line aswell. Sadly extension does only recognize one. Any fix for this?

thanks for any help.

![Screenshot from 2023-05-05 20-06-27](https://user-images.githubusercontent.com/132701569/236535253-c0070d6e-50b8-4c37-b828-a34841b546ff.png)

![Screenshot from 2023-05-05 20-06-45](https://user-images.githubusercontent.com/132701569/236535353-dd3dab80-f239-4e06-94ef-4fdfb944e91d.png)

**Comment by daitj** [comment]
Have you tried disabling the display state check from advanced settings? Also please follow the issue guidelines to get logs, it would be easier to find the solution.

**Comment by juladuni** [comment]
Yep, disabling 'display state check' solved the problem.
Thanks.
