### ISSUE TITLE
Sync with laptop display brightness

### ISSUE THREAD

**Issue by OrakMoya** [daitj/gnome-display-brightness-ddcutil#107]
Hello,

It would be nice to have an option to sync the "All" slider with the brightness value of the laptop screen.

**Comment by 42Willow** [comment]
This is a great idea.

**Comment by mihstaz** [comment]
I would also appreciate this

**Comment by ONesterkin** [comment]
Fully support this idea

**Comment by lightonflux** [comment]
Different displays have different brightness levels and progression. 

By syncing do you mean the same 0-100 value, or locking the sliders? So you could have one at 30 and one at 40, lock them together and move -5 to get 25 and 35.

**Comment by daitj** [comment]
Once #136  is finalized this should work.
