### ISSUE TITLE
Do not display devices whose brightness can't be changed by ddcutils

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [daitj/gnome-display-brightness-ddcutil#11]
The extension shows two screens in my case: my external monitor (which is correct) and a device without name (probably my laptop screen). If I change the value of the device without name, nothing happens, so in my opinion it shouldn't be displayed at all.

**Comment by themightydeity** [comment]
@P1zz4br0etch3n  could you post output of 

```
ddcutil detect
```

and 

```
ddcutil detect --brief | grep "/dev/i2c" | awk -F'/dev/i2c-' '{printf($2 "=>"); system("ddcutil getvcp --nodetect --brief 10 --bus " $2) }'
```
I will check what is happening to you.

**Comment by P1zz4br0etch3n** [comment]
Thanks for the response. There's nothing "happening to me". `ddcutil` just can't control integrated laptop screens as it's said [here](https://www.ddcutil.com/#introduction) under "Restrictions". So I think your extension shouldn't display those. `ddcutil detect` prints "Invalid display" instead of e.g. "Display 1". You could just filter those displays out.

**Comment by themightydeity** [comment]
Unless you send me the output of `ddcutil detect` and `ddcutil getvcp --brief 10 --bus $YOUR_MONITORS_I2C_BUS`  I wont be able to know what is that I need to hide.

**Comment by daitj** [comment]
No response from the OP, closing it for now.
