### ISSUE TITLE
Brightness media keys support

### ISSUE THREAD

**Issue by azmeuk** [daitj/gnome-display-brightness-ddcutil#110]
Thank you for this great extension.
Some keyboards have media keys dedicated to screen brightness. The shortcut selection dialog did not react on these key pressing so I could not bind the brightness to these keys.

**Comment by daitj** [comment]
@astrolemonade Editor is still working. Seeing "Apply" button there in your screenshot, I think you might be using an old version. 

Anyway, delete everything in the shortcut field and press "Apply" then you should be able to see shortcut editor. 

But that doesn't support special keys like brightness, for that you need to edit it manually. 

The event code for brightness up and down key are `XF86MonBrightnessUp` and `XF86MonBrightnessDown`

also `<Ctrl>` should be `<Control>` in the newer version of the extension. 

So something like 

```
<Ctrl><Alt><Shift>XF86MonBrightnessUp
```

and 

```
<Ctrl><Alt><Shift>XF86MonBrightnessDown
```
