### ISSUE TITLE
Extension doesn't seam to work with ddcutil 2.0.0

### ISSUE THREAD

**Issue by prodrigestivill** [daitj/gnome-display-brightness-ddcutil#115]
**Describe the bug**
The extension is unable to read the current brightness nor change it.

**To Reproduce**
Update to [ddcutil 2.0.0](https://github.com/rockowitz/ddcutil/releases/tag/v2.0.0).

**Delete cache file if it exists and try again**
Deleted `$XDG_CACHE_HOME/ddcutil` folder and  `$XDG_CACHE_HOME/ddcutil_detect` and still fails.

**Journal logs**
```
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                display ROG PG279Q, current: 0.33 => 0.32, new brightness: NaN, new value: 32
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                Write collector update, current countdown is 52 for 5
Nov 03 16:20:48 ddcutil[5514]: busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                display ROG PG279Q, current: 0.32 => 0.31, new brightness: NaN, new value: 31
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                Write collector update, current countdown is 44 for 5
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                Write in queue countdown over for 5
Nov 03 16:20:48 gnome-shell[4623]: display-brightness-ddcutil extension:
                                                async /usr/bin/ddcutil setvcp 10 NaN --bus 5 --sleep-multiplier 1 
Nov 03 16:20:48 gnome-shell[5514]: Not a number: "NaN"
Nov 03 16:20:48 gnome-shell[5514]: Invalid VCP value: NaN
Nov 03 16:20:48 gnome-shell[5514]: busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
Nov 03 16:20:49 ddcutil[5520]: busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
Nov 03 16:20:49 gnome-shell[5520]: Not a number: "NaN"
Nov 03 16:20:49 gnome-shell[5520]: Invalid VCP value: NaN
Nov 03 16:20:49 gnome-shell[5520]: busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
```

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - GNOME version 45
 - Extension version 46

**Additional context**
Downgraded to ddcutil to 1.4.1 and it works.

**Comment by Susanthakuri92** [comment]
Thanks

**Comment by daitj** [comment]
I built ddcutil v2.0.0 from the source https://github.com/rockowitz/ddcutil/tree/2.0.0-release and I cannot reproduce the error. It could of course be just the Arch release has some issues. 

@prodrigestivill could you post the output of in your system with 2.0.0
```
ddcutil getvcp 10 --brief --bus 5
```

**Comment by Susanthakuri92** [comment]
No monitor detected on bus /dev/i2c-5

i got this

**Comment by prodrigestivill** [comment]
The requested output is:
- Using version 1.4.1
```
$ ddcutil getvcp 10 --brief --bus 5
VCP 10 C 0 100
```

- Using version 2.0.0
```
$ ddcutil getvcp 10 --brief --bus 5
busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
VCP 10 C 0 100
```

But I'm starting to thing it might not only be a ddcutil version issue.

It is true, that I require to enable this extension setting:
 - Disable Display State Check

Otherwise no brightnes bar appear.

Here is the output using version 1.4.1 without disabling display state check:
```
gnome-shell[1887]: display-brightness-ddcutil extension:
                   ddcutil brief info:
                   Display 1
                      I2C bus:          /dev/i2c-5
                      DRM connector:    card1-DP-1
                      Monitor:          ACI:ROG PG279Q:#ASNlg6FzuzPd
                   
gnome-shell[1887]: display-brightness-ddcutil extension:
                   ddcutil brief info found bus line:
                       I2C bus:          /dev/i2c-5
gnome-shell[1887]: display-brightness-ddcutil extension:
                   ddcutil reading display state for bus: 5
gnome-shell[1887]: display-brightness-ddcutil extension:
                   ddcutil reading display status for bus: 5 is: VCP D6 ERR
```

Also as a note, I'm using nvidia propietary driver that requires the following module options (`/etc/modprobe.d/nvidia.conf`):
```
options nvidia NVreg_RegistryDwords=RMUseSwI2c=0x01;RMI2cSpeed=100
```

**Comment by trucndt** [comment]
Same issue here, it is stuck at "Initializing" with ddcutil 2.0.0

**Comment by daitj** [comment]
@prodrigestivill 
What is the output of 
```
ddcutil getvcp D6 --brief --bus 5
```
I want to know if monitor's state is detect correctly and also
```
ddcutil getvcp 10 --brief --bus 5 2>/dev/null
```
I want to know if that `busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.` message is redirected ot stdout ot stderr

Just FYI, in newer version of Nvidia driver you do not need this anymore. I do not think this is the issu though. 
```
options nvidia NVreg_RegistryDwords=RMUseSwI2c=0x01;RMI2cSpeed=100
```

**Comment by prodrigestivill** [comment]
Hello @daitj,

I removed the `NVreg_RegistryDwords` module option and it work the same way using the 1.4.1 without issues.

I also upgraded to 2.0.0 and those are the output you requested:
```
$ ddcutil getvcp D6 --brief --bus 5
busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
VCP D6 ERR
```

```
$ ddcutil getvcp 10 --brief --bus 5 2>/dev/null
busno=5. Monitor apparently returns -EIO for unsupported features. This cannot be relied on.
VCP 10 C 0 100
```

It looks like this error is printed to stdout, :(

Thanks for all the effort.

**Comment by prodrigestivill** [comment]
Perfect version 47 works with ddcutil 2.0.0!!!
Thanks!

PD: as a note the version 47 is not yet uploaded to gnome extensions repository.

**Comment by daitj** [comment]
It is already uploaded but review is pending.
