### ISSUE TITLE
Changes in ddcutil 2.0 require a new installation process

### ISSUE THREAD

**Issue by brenoferreiralima** [daitj/gnome-display-brightness-ddcutil#123]
according to https://www.ddcutil.com/i2c_permissions/ on ddcutil 2.0 and above you now need to copy:

/usr/share/ddcutil/data/60-ddcutil-i2c.rules
and
/usr/share/ddcutil/data/60-ddcutil-usb.rules
to 
/etc/udev/rules.d/

instead of /usr/share/ddcutil/data/45-ddcutil-i2c.rules (that don't exist anymore). 
Plus (in some distros, and was my case) you need to uncomment this lines:

'# KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"' from /usr/share/ddcutil/data/60-ddcutil-i2c.rules 
and
'# SUBSYSTEM=="usbmisc",  KERNEL=="hiddev*", PROGRAM="/usr/bin/ddcutil chkusbmon $env{DEVNAME} -v", MODE="0660", GROUP="video"' from /usr/share/ddcutil/data/60-ddcutil-usb.rules
 

that was what i needed to do on my system to make the extension works properly...
system info:

PKG: ddcutil 2.0.0
OS: Fedora Linux 39 x86_64
Kernel: 6.6.7-200.fc39.x86_64
DE: Gnome 45.2
WM: Mutter (Wayland)
CPU: AMD Ryzen 7 5700G (16) @ 4.67 GHz
GPU: AMD Radeon Vega Series / Radeon Vega Mobile Series

**Comment by mschubert** [comment]
On Arch, I did not need this step at all - but just add the user to the `i2c` group

**Comment by brenoferreiralima** [comment]
> On Arch, I did not need this step at all - but just add the user to the `i2c` group

yeah just installed on a new arch installation and you don't need to uncomment those lines, but the files are "60-ddcutil-i2c.rules" and "60-ddcutil-usb.rules" instead of the old "45-ddcutil-i2c.rules"
