### ISSUE TITLE
Can't access extension settings if slider is shown in control panel

### ISSUE THREAD

**Issue by ONesterkin** [daitj/gnome-display-brightness-ddcutil#126]
**Describe the bug**
When I moved the extension slider to Gnome's native system panel, next to the built-in laptop brightness slider, the extension button disappeared from the top panel (good), but I cannot access the settings of the extension anymore (bad). Other than this, the extension is working absolutely fine. Maybe I'm just missing something. 
Tried dconf-editor - but no luck, only way to revert it back to top-panel and access settings from there.

**To Reproduce**
Change the setting "Button location"  to "System panel"

**Delete cache file if it exists and try again**
Deleting cache doesn't help (it doesn't exist)

**Desktop (please complete the following information):**
 - OS: Fedora (Workstation)
 - Version 39
 - GNOME version 45.2
 - Extension version 48

**Additional context**
Screenshot of dcof-editor settings for extension:
![image](https://github.com/daitj/gnome-display-brightness-ddcutil/assets/7241193/bcda67c5-0e53-49af-9795-bed8a48faa3f)

**Comment by daitj** [comment]
This extension's settings can always be accessed from "Extensions" application that comes preinstalled with GNOME.
