### ISSUE TITLE
Extension "Settings" crashes shortly after opening

### ISSUE THREAD

**Issue by mschubert** [daitj/gnome-display-brightness-ddcutil#127]
**Describe the bug**

Opening "Settings" dialog crashes after some seconds. After that, I can also no longer open other extensions settings.

**To Reproduce**

Open the "Settings" dialog, scroll a bit

**Journal logs**

```
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
  openExtensionPrefs@resource:///org/gnome/shell/ui/extensionSystem.js:308:26
  openPreferences@resource:///org/gnome/shell/extensions/extension.js:27:26
  addSettingsItem/<@file:///usr/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:222:18
  activate@resource:///org/gnome/shell/ui/popupMenu.js:194:14
  _init/<@resource:///org/gnome/shell/ui/popupMenu.js:111:24
  @resource:///org/gnome/shell/ui/init.js:21:20
```

**Desktop (please complete the following information):**
 - OS: Arch
 - Version 2024-01-11
 - GNOME version 45.3
 - Extension version git HEAD

**Comment by daitj** [comment]
Are you using wayland session?

Somehow `this.openPreferences()` is triggering an error I suppose. Can you open settings for other extensions? 

Were there some other log entry before of after settings dialog crashed?

**Comment by ImmortAlexGM** [comment]
https://gitlab.gnome.org/GNOME/gjs/-/issues/598

**Comment by mschubert** [comment]
I updated to `gjs=1.78.3` and can confirm this issue no longer appears
