### ISSUE TITLE
Refresh displays list when display is connected/disconnected

### ISSUE THREAD

**Issue by Thesola10** [daitj/gnome-display-brightness-ddcutil#129]
**Describe the bug**
I use a USB-C display with my laptop, meaning my DDC/CI display configuration changes often as I connect and disconnect it as needed.

Currently the list of brightness sliders does not update when I connect or disconnect my external display, unless I change the button location to panel and back to system tray.

**To Reproduce**
- Connect or disconnect an external display compatible with DDC/CI

**Delete cache file if it exists and try again**
Delete `$XDG_CACHE_HOME/ddcutil_detect` which generally is `~/.cache/ddcutil_detect` and try to run extension again.

**Journal logs**
```
janv. 30 14:42:29 SolaXBook gnome-shell[2010]: JS ERROR: TypeError: this is null
                                               onMonitorChange@file:///home/karim/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:538:9
                                               _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
                                               @resource:///org/gnome/shell/ui/init.js:21:20
```
↑ looks like signals aren't being reconnected properly, leading to the handler pointing to a destroyed instance of `this`?

**Comment by daitj** [comment]
Need information on which version of the extension you are using?

**Comment by Thesola10** [comment]
v48 from GNOME Extensions

**Comment by Thesola10** [comment]
Seems fixed on GNOME 46 somehow
