### ISSUE TITLE
Update instruction for fedora

### ISSUE THREAD

**Issue by iiiian** [daitj/gnome-display-brightness-ddcutil#143]
When using fedora 40 with ddcutil 2.1.2, the content inside `60-ddcutil-i2c.rules` are all commented out by default. Hence user need to manually uncomment the line below:

```
# KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
```

please add it to the documentation

**Comment by Quantumdit** [comment]
Thanks for mentioning this, it helped me get things working (Fedora 40, ddcutil 2.1.2, gnome-display-brightness-ddcutil 49).

**Comment by daitj** [comment]
Report this to ddcutil's repo as well.
