### ISSUE TITLE
add option to also control laptop (eDP) panel brightness

### ISSUE THREAD

**Issue by kafeenstra** [daitj/gnome-display-brightness-ddcutil#145]
This extension is absolutely great!
However, working with laptop and two external monitors, I'd love to be able to adjust brightness for all three screens in one go. It seems that it would be trivial to add this for e.g. ubuntu (and probably any gnome desktop distro). 
The [Discrete Brightness app source](https://github.com/eugene-rom/discrete-brightness/blob/8b41e54e6e14af2e0d4083adb84de7d25c9fb47c/src/extension.js#L64) shows an example of two lines for reading (a few lines up) and setting (this line) laptop panel brightness through the gnome desktop.
I'd be happy to have a go at this, but may need some help at some point ;-)

**Comment by daitj** [comment]
This is already implemented in #136 which will be merged once  I am back from vacation.
