### ISSUE TITLE
Let the keyboard shortcuts control the Primary display instead of All

### ISSUE THREAD

**Issue by openaiken** [daitj/gnome-display-brightness-ddcutil#149]
The keyboard shortcuts control All Displays. I'm requesting an Enhancement to implement a toggle switch in the extension preferences that would cause the keyboard shortcuts to adjust the brightness on only the Primary Display.

My personal use case for this is that I want all of my other monitors (cheap VA panels) to stay at a static brightness level, and I like to adjust my primary display's (OLED) brightness based on the task (productivity, gaming, video playback). I would simply disable DDC/CI on all of the other displays, but one of mine doesn't have this option, so the keyboard shortcuts adjust multiple displays' brightness levels.

I can imagine several ways to implement this feature, such as: 1) Reading the Primary Display from gnome settings, 2) letting the user select a "favorite" display in the extension preferences, 3) adding toggle switches in the popup menu or the extension preferences for disabling/enabling control for each Display by the extension in general, or 4) expanding the keyboard shortcut feature to implement shortcuts for control of each individual display.

I love this extension, it is simple and elegant, and effective. Thanks for making it!

**Comment by daitj** [comment]
Would it be okay for you to just have only one display?

Then you can create a file called `ddcutil_detect` inside your `~/.cache/` directory with this command
```
ddcutil --brief detect > ~/.cache/ddcutil_detect
```

Then use a text editor to remove all the other unwanted display, disable and enable the extension.

**Comment by openaiken** [comment]
Wow! Thanks for the reply. I didn't know about this functionality. I just tried that and it basically gives me the desired behavior.

I see though that this stores the I2C bus numbers of the displays... I was under the impression that this is subject to change at every boot -- is it not? (If it's essentially static I don't technically need the extension). I might take a stab at implementing the change in a fork and seeing if you like it.

**Comment by daitj** [comment]
I2C bus are static for a specific gpu driver for specific dp or hdmi port. If you do not change those often then you should be good. 

For implementation
Same stuff above will happen to primary monitor setting if you use index, so you might need to use something like serial number or display name as primary monitor identifier in settings. If you are going to use Primary monitor from gnome then you need to find right bus for that monitor.

Then you will find relevant  stuff in `indicator.js` from line 36 where you need to read  primary monitor and just use that one instead. 
```
function sliderKeyUpDownEvent(actor, scrollStep) {
    actor.getStoredSliders().forEach(slider => {
        slider.setShowOSD();
        slider.ValueSlider.value = Math.min(Math.max(0, slider.ValueSlider.value + scrollStep), slider.ValueSlider._maxValue);
        slider.setHideOSD();
    });
}
```
