### ISSUE TITLE
Brightness sliders not present in Gnome System Menu when system menu is selected in extension preferences.

### ISSUE THREAD

**Issue by GSF1200S** [daitj/gnome-display-brightness-ddcutil#150]
**Describe the bug**
No brightness sliders when extension is set to use system menu; works fine when set in top bar. This just started happening with the most recent extension update.

**To Reproduce**
Open Gnome system menu with the extension set to display the sliders there. No sliders appear. You can scroll on the brightness icon present on top-bar and it will adjust brightness; the sliders however again are not present.

**Delete cache file if it exists and try again**
Delete `$XDG_CACHE_HOME/ddcutil_detect` which generally is `~/.cache/ddcutil_detect` and try to run extension again.
Done. Same issue.

**Journal logs**
You need to enable `Verbose debugging` from this extension's settings and then reload this extension first.
```
journalctl --no-pager -b /usr/bin/gnome-shell

Sep 08 21:38:59 geekdomv2 gnome-shell[2132]: JS ERROR: TypeError: item.slider is undefined
                                             _reloadMenuWidgets/<@file:///home/gsf1200s/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:461:34
                                             _reloadMenuWidgets@file:///home/gsf1200s/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:456:51
                                             reloadMenuWidgets/_reloadMenuWidgetsTimer<@file:///home/gsf1200s/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:409:18
                                             setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9
                                             @resource:///org/gnome/shell/ui/init.js:21:20

```
**Screenshots**
Pretty sure this isn't necessary as it's pretty self-explanatory. If you need screenshots I can provide them.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 40 Workstation
 - GNOME version: 46
 - Extension version: 50

**Additional context**
N/A

**Comment by daitj** [comment]
Yeah recent update had some new settings which where enabled by default, i pushed a new update which should fix that. 

If you enable "All" sliders then you should be able to have rest of the display sliders as child slider in the quick settings.

**Comment by GSF1200S** [comment]
Thanks for the clarification- having it in the system settings menu is definitely better for me!

Consider that for dual/more screen users this requires another click to get to the brightness controls for each monitor, though. You must click to open Gnome's System Settings, click the little arrow next to the all brightness slider, and then click each slider; before you opened Gnome's System Settings, and both sliders were already shown to click on. Perhaps in a future update you might have a "Show all sliders in System Settings" or something like that. Doesn't make much difference to me though I probably prefer it the old way :)

Thanks for your contribution- I used to have bash aliases doing ddcutil commands before this extension :D
