### ISSUE TITLE
60-ddcutil-i2c.rules does not exist on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by seb-1204** [daitj/gnome-display-brightness-ddcutil#155]
**Describe the bug**
instructions state to copy `/usr/share/ddcutil/data/60-ddcutil-i2c.rules` to /etc/udev/rules.d

In my Ubuntu 24.04.1 the file `60-ddcutil-i2c.rules` does not exist. I have however 

```
$ cat /usr/share/ddcutil/data/45-ddcutil-i2c.rules 
# On some distributions, package i2c-tools provides a udev rule. 
# For example, on Ubuntu, see 40-i2c-tools.rules. 

# Assigns the i2c devices to group i2c, and gives that group RW access:
KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"

# Gives everyone RW access to the /dev/i2c devices: 
# KERNEL=="i2c-[0-9]*",  MODE="0666"

```

As I have updated through various LTS releases I am not 100% if this is a me issue or a current Ubuntu LTS issue.

I also noted that the last row was mentioned for Fedora users.

**To Reproduce**
Steps to reproduce the behavior: try to copy the file, system will tell you it does not exist.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 24.04.01
 - GNOME version 46
 - Extension version latest

**Additional context**

**Comment by seb-1204** [comment]
Oh, I see Ubuntu 24.04.01 still comes with ddcutil 1.4.1. That might be it?

**Comment by daitj** [comment]
Yes it is already mentioned on the readme
