### ISSUE TITLE
Upgrading to the new version failed

### ISSUE THREAD

**Issue by coot** [daitj/gnome-display-brightness-ddcutil#16]
The error recorded in `/var/log/messages`:
```
Feb 17 11:00:46 fozzie gnome-shell[3747]: JS ERROR: Extension display-brightness-ddcutil@themightydeity.github.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:342:52#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:222:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

gnome-shell: `Version: 3.38.3-2`

**Comment by daitj** [comment]
@coot Have you tried restarting your gnome shell `Alt+F2` > `r` 
OR
If you are using Wayland then logout and login. 

Lets see what happens. 

Have you been installing the extension from gnome extension site? or from the source i.e. this repo?

**Comment by coot** [comment]
Thanks, I was able to reinstall it now, probably `gnome-shell` restart was enough.
