### ISSUE TITLE
Not compatible with Gnome 40.

### ISSUE THREAD

**Issue by karuboniru** [daitj/gnome-display-brightness-ddcutil#17]
Upon upgrading to Gnome 40.beta.0, the extension stopped working. 

Some [migration work](https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/) might be needed.

**Comment by daitj** [comment]
Yeah, the extension will require some rework. I cannot give any ETA yet. But once it is avaiable in my distro, I will look into this.

**Comment by daitj** [comment]
@karuboniru 
I have added just published a new version with some bug fixes and support for gnome40
