### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by Razer0123** [daitj/gnome-display-brightness-ddcutil#21]
In my keyboard i have shortcuts to reduce and increase brightness

Any way to add support for this using your extension?

This might look stupid but might actually increase my life well being

**Comment by daitj** [comment]
It would nice feature to have that, I haven't looked into that yet. Just in general to have keyboard shortcuts controlling the brightness.

I am bit busy at the moment. if someone else is willing to add it and make a pull request, I am more than happy.

**Comment by Razer0123** [comment]
Seems like no help is coming, but i would be willing to contribute economically to have this feature

**Comment by daitj** [comment]
Currently I am busy to look into this, because it is not just to add some fixed shortcut, but users should have possiblity to set the shortcut themselves. 

I have added a label so that it will be highlighted for passerby, may be someone will be interested to grab the bounty you are willing to contribute.

**Comment by Razer0123** [comment]
Just wondering, would it be easy just to add support to media brightness shortcuts? (like the one present in laptops or in some keyboards, like raising volume media shortcuts)

**Comment by Razer0123** [comment]
Or we could simply add an option to select a shortcut in the extension

**Comment by cnrrobertson** [comment]
> Until there's a good solution I'll use `gnome-control-center` → Keyboard → Customize Shortcuts → Custom Shortcuts for this:
> 
> ```shell
> # increment by 10
> bash -c "ddcutil setvcp 10 $(expr $(ddcutil getvcp 10 | tr -dc ' 0-9' | awk '{print $(NF-1)}') + 10)"
> 
> # decrement by 10
> bash -c "ddcutil setvcp 10 $(expr $(ddcutil getvcp 10 | tr -dc ' 0-9' | awk '{print $(NF-1)}') - 10)"
> ```
> 
> (some `Math.max(x, 0)` and `Math.min(x,100)` should be added to avoid obvious errors with out of range values.)

This is the solution I ultimately went with. But I noticed that the ddcutil setvcp already has plus minus built in (makes for a simpler shortcut):
```shell
# increase by 10
ddcutil setvcp 10 + 10

# decrease by 10
ddcutil setvcp 10 - 10
```
It also gracefully handles out of range.

**Comment by Razer0123** [comment]
> > Until there's a good solution I'll use `gnome-control-center` → Keyboard → Customize Shortcuts → Custom Shortcuts for this:
> > ```shell
> > # increment by 10
> > bash -c "ddcutil setvcp 10 $(expr $(ddcutil getvcp 10 | tr -dc ' 0-9' | awk '{print $(NF-1)}') + 10)"
> > 
> > # decrement by 10
> > bash -c "ddcutil setvcp 10 $(expr $(ddcutil getvcp 10 | tr -dc ' 0-9' | awk '{print $(NF-1)}') - 10)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (some `Math.max(x, 0)` and `Math.min(x,100)` should be added to avoid obvious errors with out of range values.)
> 
> This is the solution I ultimately went with. But I noticed that the ddcutil setvcp already has plus minus built in (makes for a simpler shortcut):
> 
> ```shell
> # increase by 10
> ddcutil setvcp 10 + 10
> 
> # decrease by 10
> ddcutil setvcp 10 - 10
> ```
> 
> It also gracefully handles out of range.

Tried and works, not sure why but the media button brightness down seem to work this way, but not brigthness up

**Comment by daitj** [comment]
This is added in the new version of the extension, thanks to @oscfdezdz
