### ISSUE TITLE
Hide indicator when no monitor is connected for a few minutes

### ISSUE THREAD

**Issue by oscfdezdz** [daitj/gnome-display-brightness-ddcutil#29]
It could be hidden when one minute passes and no monitor has been connected. When one is connected it would show up again.
A switch would be ideal to change this behavior from the preferences.

EDIT: This can be thought the other way around, showing when a monitor is detected.

**Comment by daitj** [comment]
@oscfdezdz do you still want this to be implemented?

Because we can already hide indicator in system menu?

**Comment by cenktaskin** [comment]
I'm not the issuer, but it would be nice to have!

**Comment by oscfdezdz** [comment]
> @oscfdezdz do you still want this to be implemented?
> 
> Because we can already hide indicator in system menu?

Well, this issue was opened before button location preference was implemented. Now, I use system menu option without indicator and sliders do not show when there are no connected monitors.

I guess it would be useful for those having the indicator when using system menu option or top bar one.

**Comment by daitj** [comment]
I have added so that the icon will be hidden if there are no monitors detected, let me know if this behaves properly.
