### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by LordVicky** [daitj/gnome-display-brightness-ddcutil#31]
> `
sudo cp /usr/share/ddcutil/data/45-ddcutils-i2c.rules /etc/udev/rules.d
`

Here 45-ddcutils shouldn't have  a 's' and gives error while executing, 

hence:

`sudo cp /usr/share/ddcutil/data/45-ddcutil-i2c.rules /etc/udev/rules.d`

**Comment by daitj** [comment]
Fixed now, thanks for pointing it out.
