### ISSUE TITLE
Gnome 41 compatibility

### ISSUE THREAD

**Issue by steffen-stell** [daitj/gnome-display-brightness-ddcutil#32]
This extension is great, thank you! Unfortunately, as of now it is not compatible with Gnome 41, thus I have to live without it on the recently released Fedora 35. An update would be wonderful

**Comment by saknl** [comment]
I edited the metadata.json and it works just fine on Gnome 41.1.

**Comment by steffen-stell** [comment]
Thanks, I wasn't aware that it is that easy to do

**Comment by daitj** [comment]
This is fixed now.
