### ISSUE TITLE
Slider in system menu is not removed when reloading the extension

### ISSUE THREAD

**Issue by oscfdezdz** [daitj/gnome-display-brightness-ddcutil#41]
I noticed the change with the last commit 68f9a12462bb13da178af4509195d73f97c91c8e, adding `mainMenuButton.removeAllMenu()` before disabling the extension in `reloadExtension` function solves it, but looking at the changes in the code I do not see where the bug comes from, that is why I open this issue.

**Comment by daitj** [comment]
This is something I am trying to figure out as well, I have check examples from some other extensions on how have they been approaching to this. Even though indicator and menu are destoryed the items are still visible. I will try to figure this out later today
