### ISSUE TITLE
Sliders don't change ddc values

### ISSUE THREAD

**Issue by jacksongoode** [daitj/gnome-display-brightness-ddcutil#43]
It seems like the latest update broke functionality for me. The sliders move but the values do not change.

**Comment by daitj** [comment]
Could try the latest version from github and see what happens? I wonder if you have samme issue as #44. I will try to publish a new version after I fix some outstanding issue later today.

**Comment by Razer0123** [comment]
Confirmed not working anymore after latest update

**Comment by daitj** [comment]
@Razer0123  have you tried the github version? could you share some gnome-shell log?

**Comment by daitj** [comment]
I just pushed a new version, it should be up once review is finalized.
