### ISSUE TITLE
ERROR: console is not defined

### ISSUE THREAD

**Issue by mutlucan96** [daitj/gnome-display-brightness-ddcutil#44]
I performed the steps on the tutorial and I can change brightness without root. Also [this extension](https://extensions.gnome.org/extension/4652/adjust-display-brightness/) works fine.
When I install from Gnome Extensions, I get an error. (console is not defined). I see the icon on the system menu but nothing else.
I also tried to install from source but it didn't go well, too. 
![Screenshot from 2022-01-06 09-23-11](https://user-images.githubusercontent.com/42113538/148338250-b56a3db4-9d4c-4200-aaa7-f77caef67434.png)

**Comment by vdemonchy** [comment]
+1 on this, same issue just appeared for me as well since the latest update has been installed
