### ISSUE TITLE
Suddenly stopped working 

### ISSUE THREAD

**Issue by tobealive** [daitj/gnome-display-brightness-ddcutil#46]
Hey hello, I'm using this great tool every day last time yesterday evening. It suddenly stopped working now.

- No nothing happens on extension icon click
- It got automatically disabled in the extensions and shows an error icon that's not giving further information on the issue
- Reinstallation doesn't solve the issue
![Selection_003](https://user-images.githubusercontent.com/34311583/148387285-bc6c0067-a1cc-4f6d-81a8-1268610cdd86.jpg)

**Comment by ekah321** [comment]
![Screenshot from 2022-01-06 18-45-07](https://user-images.githubusercontent.com/81580123/148388467-5d891f2e-792d-4497-93e4-c90026193dee.png)
After update, stopped working. What is 'console is not defined'?

**Comment by daitj** [comment]
Well apparently in some systems console is not available, which is used for logging things to the console. 

Anyway new version is already being pushed, which should fix the problem, meanwhile you could install it manully from here.

**Comment by tobealive** [comment]
Thank you!
