### ISSUE TITLE
system freeze on reload

### ISSUE THREAD

**Issue by dr1s** [daitj/gnome-display-brightness-ddcutil#48]
The issue seems to be that every reload is clicked a new `ddcutil` process is spawned.
So if you hit reload multiple times in a short period of time, the system basically freezes up.

I don't intend to do this again, but maybe its possible to limit the amount of processes spawned?

**Comment by daitj** [comment]
In my hardware `ddcutil detect --brief` freezes up the whole system, but only for the first time. Can you check if your system also freezes when that happens and also could you check if it happens everytime?

Last time I tried to debug this, after booting (when extension was disabled) I ran this command one by one for all the bus `ddcutil capabilities --bus ${bus_numer}` , I found out that bus number 1 was the problem which ended up freezing the system.

In this project's  [README](https://github.com/daitj/gnome-display-brightness-ddcutil#screen-hangslocks-on-first-startup), there is a workaround. If your `$XDG_CACHE_HOME` is empty then file should be inside `~/.cache`

**Comment by dr1s** [comment]
The problem also happens with the cache workaround, but i never noticed anything on first startup.

I just tried it again and if i just click 3 times on the reload button in the settings i see up to 93 ddcutil processes waiting.

**Comment by daitj** [comment]
Are you using the latest version of the extension, 93 proceses seems awfully lot. 

Each reload should trigger 1 + number of monitors you have requests. This is what is happening for me when I am testing at least.


Could you share these information, may be I could try to run similar environment in libvirt and check it out. 
**Journal logs**
```
journalctl --no-pager -b /usr/bin/gnome-shell
```

**Desktop :**
 - OS: [e.g. Debian]
 - Version [e.g. 11]
 - GNOME version [e.g. 40.1]
 - Extension version [eg: 10]

**Comment by will-lol** [comment]
I am also having this issue. Only on the latest extension version though.
