### ISSUE TITLE
Show OSD indicator, when changing brightness via keyboard or scrolling over icon in panel

### ISSUE THREAD

**Issue by sojusnik** [daitj/gnome-display-brightness-ddcutil#57]
It would help, if an OSD indicator would appear, when changing the brightness via keyboard or scrolling over the [icon in the panel](https://github.com/daitj/gnome-display-brightness-ddcutil/issues/28), analogues to the default volume OSD in Gnome, as shown here:

![grafik](https://user-images.githubusercontent.com/1245718/157003972-05e27ab3-9404-47c4-905c-0f57290f86fd.png)

**Comment by oscfdezdz** [comment]
I have this working locally, I'll submit a PR soon.
