### ISSUE TITLE
Working version for Gnome 3.36?

### ISSUE THREAD

**Issue by BerkayTutal** [daitj/gnome-display-brightness-ddcutil#59]
![image](https://user-images.githubusercontent.com/5060585/157288404-f62a7fb6-22ed-406a-a761-88262a190ce0.png)

I could not find any settings page from the installation. I've checked gnome-tweaks. I couldn't find any information on documentation too.

Package installed from https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/

Then I've tried to install manually but on "make build" it gives segmentation fault:
![image](https://user-images.githubusercontent.com/5060585/157288802-2c3e0fcd-6f3b-483d-9ffd-71c7f575b285.png)

I'm a bit new on Ubuntu so please don't be so harsh. 

Thank you!

**Comment by oscfdezdz** [comment]
The error given by `make` is because `dist` directory is missing inside extension folder.

**Comment by daitj** [comment]
I am closing this for now, if you have some issues please do reopen it.

**Comment by BerkayTutal** [comment]
I'm on the latest version 20.04 Ubuntu desktop.

I've installed it manually after creating "dist" folder and it worked after logging out and logging in but when I click settings button on the extension or the same settings button on "Extensions" page it gives me this error and I am not able to see settings:

![image](https://user-images.githubusercontent.com/5060585/157388288-69dbb91e-1034-4fa1-8858-69784b63e125.png)
![image](https://user-images.githubusercontent.com/5060585/157388328-2c1a10c6-8c90-4507-b5dc-a06c22af74bb.png)
![image](https://user-images.githubusercontent.com/5060585/157387684-e7d366f8-3691-43e7-abb7-ac74781fde20.png)


> Could you tell me which version of Ubuntu you are using? It could be that you are using very old version of the extension ( old Ubuntu = old gnome-shell = old extension) In current version of gnome-shell, all extension related settings are moved to a standalone app called "Extensions" , could you check that ?
> […](#)
> On March 8, 2022 7:08:09 PM GMT+02:00, BerkayTutal ***@***.***> wrote: ![image](https://user-images.githubusercontent.com/5060585/157288404-f62a7fb6-22ed-406a-a761-88262a190ce0.png) I could not find any settings page from the installation. I've checked gnome-tweaks. I couldn't find any information on documentation too. Package installed from https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/ Then I've tried to install manually but on "make build" it gives segmentation fault: ![image](https://user-images.githubusercontent.com/5060585/157288802-2c3e0fcd-6f3b-483d-9ffd-71c7f575b285.png) I'm a bit new on Ubuntu so please don't be so harsh. Thank you! -- Reply to this email directly or view it on GitHub: #59 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

**Comment by daitj** [comment]
@BerkayTutal The last version of this extension to support gnome 3.36 was version 7, there were not that many features and also it had some bugs.  Actually you couldn't do much via settings either, just add one extra "All" slider.  

I have to suggest you to upgrade Ubuntu to 21.10 (which has gnome 40) or if you want LTS, then wait for a month when they release 22.04.

**Comment by BerkayTutal** [comment]
> @BerkayTutal The last version of this extension to support gnome 3.36 was version 7, there were not that many features and also it had some bugs. Actually you couldn't do much via settings either, just add one extra "All" slider.
> 
> I have to suggest you to upgrade Ubuntu to 21.10 (which has gnome 40) or if you want LTS, then wait for a month when they release 22.04.

I'll probably wait for a month more to have the LTS version, thank you!

Could you help me to understand this in detail, why can't we release a version to work with 3.36 too? Are there a lot of differences between the two as libraries or how they work?

**Comment by daitj** [comment]
@BerkayTutal 

It is because how GNOME (gnome-shell) update usually brings new features and also the way extensions should be written.

There were some small changes from 3.36 to 3.38 but 3.38 to 40 brought lots of changes. I had to change the way extension's preference worked, for example. 

People with a stable distro like Debian stable, or Ubuntu LTS  are usually stuck with older version of the extension because of old gnome-shell. 

So to keep with the latest changes to GNOME we also have to update the way extension works.
