### ISSUE TITLE
Is there a way to use the brightness controls on the keyboard?

### ISSUE THREAD

**Issue by BierDav** [daitj/gnome-display-brightness-ddcutil#66]
I know that there is the shorcut section, but is it possible to assign them to the brightness control buttons on your keyboard? If there is, how? Otherwise: It would be very handy :)

**Comment by eumpf0** [comment]
I was trying to do the same thing, figured it out and it's working flawlessly for me.


I looked around in the dconf/gsettings database using dconf-editor and found the following keys:

`screen-brightness-down-static`, `screen-brightness-down`   (for _decreasing_ brightness)
`screen-brightness-up-static`, `screen-brightness-up`   (for _incresing_ the brightness)

under `org.gnome.settings-daemon.plugins.media-keys`

Then read/get the corresponding values using _gsettings_ or dconf-editor, e.g. type
`gsettings get org.gnome.settings-daemon.plugins.media-keys.screen-brightness-up-static` in a terminal.

In my case the values from the `-static` keys where set whereas the others were empty, but it might be different in your case.

Then use the values (the non empty output of the command above **without** the `['...']`) as the corresponding keybinding in the _brightness controll using ddcutil_ settings (just the plain values **without** any angle brackets etc.).

If all else fails it might be worth a try to just search around in the gsettings/dconf database maybe looking for keywords like "keybinding", "brightness" or something of the sort.

Hope that helps :)

**Comment by daitj** [comment]
There was a typo in @eumpf0 reply, you had a . instead of space, I have edit and fixed that.

```
gsettings get org.gnome.settings-daemon.plugins.media-keys screen-brightness-up-static
```
If you are using X11, it will have output like this: 
```
['XF86MonBrightnessUp']
```

For more XF86 keyboard symbols : [XF86keysym.h](https://github.com/freedesktop/xorg-x11proto/blob/master/XF86keysym.h)
