### ISSUE TITLE
Better keyboard shortcut editor in the preferences, which captures and sets pressed keys.

### ISSUE THREAD

**Issue by SebastianGrans** [daitj/gnome-display-brightness-ddcutil#69]
Currently, the default keyboard bindings are `<Ctrl><Alt><Shift>h` and `<Ctrl><Alt><Shift>g`, but in my opinion it makes more sense to have them default to `XF86MonBrightnessUp` and `XF86MonBrightnessDown`. This way it will directly work with keyboards which have brightness keys (in my case a Keychron C1). 

Not everyone knows about these XF86 keyboard symbols, so it would be logical to make it easier for people. :) 

Another improvement would be to implement the same key entry method as they have in GNOME Control Center where you simply press the key/key combo that you want for the keybinding. (See screenshot below) The implementation of that is available here: [link](https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/keyboard/cc-keyboard-shortcut-editor.c)

What is your opinion on this? 

![Screenshot from 2022-04-20 14-16-57](https://user-images.githubusercontent.com/10030015/164228775-0e8e8755-8383-4d35-a449-6f719dd1b445.png)

**Comment by daitj** [comment]
If we use `XF86MonBrightness*` default keybindings will conflict with gnome's own keybinding, for laptops this might be an issue. So may be something like `Ctrl + XF86MonBrightness*` would make sense, then about grabber for keyboard shortcut, I need to do some research on this, I do not want to reinvent the wheel, if there are some ways to call the same components from gnome control panel, it would be great. 

@oscfdezdz Since you were working with the shortcut stuff, would you like to look into this? I can also check it when I am free.

**Comment by SebastianGrans** [comment]
I didn't consider laptop users. Then using `Ctrl` as a modifier makes more sense. 

If I have some spare time, I'll try implementing the keyboard shortcut grabber in GJS.

**Comment by daitj** [comment]
@SebastianGrans 

GTK4 ui for shortcut editor can be found in gnome-control-center source here: [cc-keyboard-shortcut-editor.ui](https://github.com/GNOME/gnome-control-center/blob/master/panels/keyboard/cc-keyboard-shortcut-editor.ui)

It should be fine to copy that (as GNOME uses GNU GPL) and then add some extra gjs stuff for our use case.

**Comment by BierDav** [comment]
I would really like to see that. But how to achive that as of now?
![image](https://user-images.githubusercontent.com/46626041/166098251-b8ab1acd-e2ec-4689-891f-13085fbf1b10.png)

`XF86MonBrightness`, `XF86MonBrightness*`, `XF86_MonBrightness` and `XF86MonBrightness*` don't work.

**Comment by daitj** [comment]
@BierDav could you check if you brightness key is working, `sudo showkey` or `xev` (for X11) will help you with that.  

For gui option you could also go to Settings > Keyboard > View and customize shortcuts  > try to add shortcut and see if brightness key gets detected.

**Comment by BierDav** [comment]
Oh you are right. I haven't divorced my Brightness Key in solaar. Thanks ;)

**Comment by oscfdezdz** [comment]
> @oscfdezdz Since you were working with the shortcut stuff, would you like to look into this? I can also check it when I am free.

Sorry for the wait, my intention when adding the keyboard shortcuts was to do it the proposed way, following GNOME's Control Center layout, but I ended up discarding it because it didn't work at the time. I will try to take a look at it and see what I can do.
