### ISSUE TITLE
Configure udev to set i2c group as owner of i2c devices

### ISSUE THREAD

**Issue by Hvalfisk** [daitj/gnome-display-brightness-ddcutil#71]
I was unable to set display brightness without sudo when using ddcutil, and the extension didn't work either.

In the notes at https://wiki.archlinux.org/title/backlight#External_monitors I found

> To facilitate binding screen brightness control to a keyboard shortcut, it may be convenient to enable non-superuser access to the relevant I2C devices. This can be achieved by adding a group i2c and configuring udev to set this group as the owner of the I2C devices. See https://raspberrypi.stackexchange.com/a/4472

And in that link it says to do

    # echo 'KERNEL=="i2c-[0-9]*", GROUP="i2c"' >> /etc/udev/rules.d/10-local_i2c_group.rules

Now the extension works and I can set brightness using ddcutil without sudo.

**Comment by daitj** [comment]
That is already in the step 4 in setup section of [README.md](https://github.com/daitj/gnome-display-brightness-ddcutil#setup-ddcutil) of this extension.
