### ISSUE TITLE
Settings for icon's position on system indicator region

### ISSUE THREAD

**Issue by n3thshan** [daitj/gnome-display-brightness-ddcutil#75]
This setting just doesn't work. The brightness icon in the system menu is always is in the last position no matter which position value i choose in the extension settings.

**Comment by daitj** [comment]
@n3thshan The position settings for icon is actually missing, the current settings is just for the whole menu, I will look into this at some point and add it.

**Comment by daitj** [comment]
This is added now in the new version.
