### ISSUE TITLE
Put the monitor sliders in a submenu in the system menu

### ISSUE THREAD

**Issue by 2nv2u** [daitj/gnome-display-brightness-ddcutil#77]
If all sliders is enabled and it's has been added to the system menu, please make the all sliders a submenu to show all the monitors and put the all one on the submenu item (no text), it would make it look like the regular slider with an arrow next to it.

Created a small concept:
![brightness-concept](https://user-images.githubusercontent.com/69992184/175833044-725d08f1-eca0-4d6d-ae33-e14baed0e3a1.jpg)
(Took the liberty of adding [Issue #76](https://github.com/daitj/gnome-display-brightness-ddcutil/issues/76) to it too)

**Comment by daitj** [comment]
I will try to check this, if there is a simple way to do it like to reuse current items and just make a submenu out of it, but I cannot give any ETA on this.

**Comment by CorvetteCole** [comment]
This would be awesome! I may have a look at it if I have time

**Comment by daitj** [comment]
Once #136  is finalized this should work
