### ISSUE TITLE
[Feature Request] Disabling Control for Specific Monitors

### ISSUE THREAD

**Issue by KaiserCalm** [daitj/gnome-display-brightness-ddcutil#79]
![image](https://user-images.githubusercontent.com/81613945/183254345-6accf3be-bc6d-4e92-9d38-af5b69b3a382.png)

I have a monitor that I want to always stay at 100%, so a nice feature would be to hide/disable controls for a specific monitor.

**Comment by daitj** [comment]
Seems like you have only two monitor so may be you should use cache file which will only show only one monitor.

```
ddcutil --brief detect > $XDG_CACHE_HOME/ddcutil_detect
```
Note: if `$XDG_CACHE_HOME` is emtpy then it is  most probably `~/.cache`.

Edit that file and remove the monitor you do not need. 

You need to explain a bit more why you need this setup though, if this doesn't help you.
