### ISSUE TITLE
GNOME 43 Support

### ISSUE THREAD

**Issue by oscfdezdz** [daitj/gnome-display-brightness-ddcutil#84]
Preferences window works but some changes to make it work with the new [Quick Settings](https://gjs.guide/extensions/upgrading/gnome-shell-43.html) will be required.

**Comment by daitj** [comment]
I will work on this once 43 comes to Debian Unstable (sid), this should be easier than before but of course need a bit of rewrite.

**Comment by daitj** [comment]
I have added a dirty fix for GNOME 43, the QuickSliders are not really useful for us, as they do not provide any text labels.

As of now the poistion in the system menu does not work, which I need to check later on. But for now we have a working version.

**Comment by crimist** [comment]
Not familiar with GNOMEs internals but would it be possible to have all monitors slider like the speaker slider and then the dropdown reveals individual monitors?

![image](https://user-images.githubusercontent.com/20033376/199323002-81a2e217-4a01-4e84-8775-e86df08ec121.png)
