### ISSUE TITLE
Brightness steps 0-5 don't work

### ISSUE THREAD

**Issue by sojusnik** [daitj/gnome-display-brightness-ddcutil#88]
**Describe the bug**
When decreasing the brightness to steps below 5, then the brightness doesn't continue to decrease, although it works with [this](https://extensions.gnome.org/extension/4652/adjust-display-brightness/) extension. In other words, when your extension sets the brightness level to 6, my monitor also shows 6 as the brightness level, but when your extension sets it to 5, then my monitor shows 0 as the brightness level, thus skipping the steps from 4 to 1.

**To Reproduce**
Decrease the brightness to 4 or lower and you'll see that the brightness won't change and stays on the lowest level.

**Journal logs**
```
Nov 26 21:44:06 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Increase brightness
Nov 26 21:44:09 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Increase brightness
Nov 26 21:44:11 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Increase brightness
Nov 26 21:44:12 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:13 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:14 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:16 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:17 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:18 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:19 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
Nov 26 21:44:20 mir gnome-shell[3443]: display-brightness-ddcutil extension:
                                       Decrease brightness
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.10
 - GNOME version: 43
 - Extension version: 32

**Comment by daitj** [comment]
This is expected behaviour, as the slider in settings didn't really go to zero when scrolling in GNOME 3.6, so I had to add that if it lower than 5 then make it 0. I tested this again in GNOME 43, that issue no longer exists, so new version of the extension will contain a fix for this.
