### ISSUE TITLE
Extension stops working after some time

### ISSUE THREAD

**Issue by sojusnik** [daitj/gnome-display-brightness-ddcutil#89]
**Describe the bug**
After some time, for no apparent reason, your extension stops to work, i.e. the brightness slider isn't shown in the system menu anymore, as the keyboard shortcuts stop to work.

What's the best way to debug this?

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.10
 - GNOME version: 43
 - Extension version: 32

**Comment by daitj** [comment]
You need to check the gnome shell log, how to get it is in the issue template. See what happens to the extension there.
