### ISSUE TITLE
Where is extension settings window?

### ISSUE THREAD

**Issue by xbillion** [daitj/gnome-display-brightness-ddcutil#91]
I was changing settings and accidentally removed the extension icon. How do I open the extension settings window?
![Снимок экрана от 2022-12-13 23-51-44](https://user-images.githubusercontent.com/63469252/207430737-5c2a8eda-8366-41e8-b9c9-2a4b3c0396a5.png)

**Comment by xbillion** [comment]
or where is config file? and how to reload extention? i've tried reinstall extention, but it is still with last config

**Comment by daitj** [comment]
Since GNOME 40, you have an app called "Extensions" from where you can open the settings for this extension.

**Comment by xbillion** [comment]
Thank you very much!

**Comment by domdomegg** [comment]
On Ubuntu 22.04, the Gnome Extensions app is not installed by default. Instead, you can get back into the settings by doing either of:
* Run `gnome-extensions prefs display-brightness-ddcutil@themightydeity.github.com`
* Click the settings icon from https://extensions.gnome.org/local/ (requires chrome-gnome-shell, installed by default)
