### ISSUE TITLE
Violates Gnome Extension Guidelines for Excessive Logging

### ISSUE THREAD

**Issue by CorvetteCole** [daitj/gnome-display-brightness-ddcutil#97]
Please refer to https://gjs.guide/extensions/review-guidelines/review-guidelines.html#no-excessive-logging.

Your logging is too verbose.

**Comment by daitj** [comment]
Thanks for the report, in early days of extension there were many issues with the extension, that is  why logging was so verbose. But from now on the extension will be quiet. I always thought I will write this someday but you issue made be actually do it.
